# NOTE: Paths are relative to the vlang/doom repository root !
# The capture screen size is 800x600 @ 24bit color depth.

# Defaults
[compare]
	method = 'idiff'
	flags = ['-p','-fail 0.001','-failpercent 0.2']

[capture]
	method = 'generic_screenshot'
	wait_ms = 7500 # After 7.5 seconds, the game *should* have started, and rendered a stable image.
	flags = ['-testcontrols', '-nosound', '-iwad', '/home/runner/doom1.wad', '-width', '800']

[[apps]]
	path = 'chocolate-doom/src/doom/doomv'
	[apps.capture]
	regions = [
		{ x = 0,   y = 0, width = 358, height = 600 } # Left half, not including the doom guy.
		{ x = 444, y = 0, width = 358, height = 600 } # Right half, not including the doom guy.
		{ x = 0,   y = 0, width = 800, height = 507 } # Top part, game screen, not including the doom guy.
	]

[[apps]]
	path = 'chocolate-doom/src/chocolate-doom'
	[apps.capture]
	regions = [
		{ x = 0,   y = 0, width = 358, height = 600 } # Left half, not including the doom guy.
		{ x = 444, y = 0, width = 358, height = 600 } # Right half, not including the doom guy.
		{ x = 0,   y = 0, width = 800, height = 507 } # Top part, game screen, not including the doom guy.
	]
